[project]
name = "fastapi-hello-world"
version = "0.1.0"
description = "Example how to get started with fastapi in a pixi environment."
authors = ["Wolf Vollprecht <wolf@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/prefix/pixi"
readme = "README.md"

[tasks]
start = "python -m uvicorn main:app --reload"

[dependencies]
python = "<=3.11.9"
uvicorn = ">=0.12.0"
fastapi = "0.110.*"
